gravwell/wiki

quickstart/community-edition.md
Thought I'd make this change for you. Please verify the md5sum from your servers.
=> Updated documentation for Gravwell Community 2.2.1 release.

ingesters/ingesters.md
=> Add sqsIngester documentation

search/ipfix/ipfix.md
just adding the flowDuration shorthand operator on ipfix
=> adding ipfix flowDuration to the set of documented shorthand modules

configuration/accelerators.md, configuration/parameters.md, search/packet/packet.md
=> Improve parameters documentation & fix-up accelerators page

api/misc.md
just updating the described routes for pulling back searchmodule and rendermodule lists
=> update API docs for searchmodules and rendermodules

changelog/3.3.1.md, changelog/3.3.2.md, changelog/3.3.4.md, changelog/3.3.5.md, changelog/3.3.7.md, changelog/4.0.0.md, configuration/hardening.md, ingesters/ingesters.md
cherry-picking 13b01594307724e7ed1117e915e7588602339c57
=> cherry picking to fix broken links in master

changelog/3.3.1.md, changelog/3.3.2.md, changelog/3.3.4.md, changelog/3.3.5.md, changelog/3.3.7.md, changelog/4.0.0.md, configuration/hardening.md, ingesters/ingesters.md
links had absolute paths with hostnames and/or pointed to hosted sub directory.
=> fixing improper link paths that assumed hosting at a specific location

search/search.md
=> document comment support

quickstart/downloads.md
=> fixing label on ingester downloads

scripting/anko.md
=> update and linkify anko documentation

ingesters/ingesters.md
=> add stanza examples for all ingesters

search/table/table.md
=> add table render format docs

configuration/caveats.md
=> add max_map_count to caveats

api/ingest.md
Adding note about the source field in the ingest API
Fixes #149
=> addressing issue 149

ingesters/preprocessors/preprocessors.md
=> document src router preprocessor

api/login.md, api/websocket-example-code.md
=> fixing API example code and auth sections

ingesters/ingesters.md
=> adding HTTP HEC configuration block examples and fixing some spelling

scripting/scriptingsearch.md
=> adding block about SQL to scripting docs

search/complete-module-list.md, search/entropy/entropy.md, search/math/math.md, search/processingmodules.md
=> move entropy to its own article and expand language

architecture/architecture.md, beta/index.md, configuration/parameters.md, quickstart/community-edition.md
Fixes #270 
Fixes #288 
Fixes #308
=> Fix apt-key references, links in global parameters, minimum requirements and version locking documentation

changelog/list.md
=> forgot to push change log list change

search/complete-module-list.md, search/extractionmodules.md, search/processingmodules.md
=> Add brief descriptions to module lists

quickstart/quickstart.md
Add some headers to explain each step and require that people copy line by line to reduce the chance for bad copypasta
=> modify the quickstart blocks 

search/complete-module-list.md, search/extractionmodules.md, search/path/path.md
=> add path documentation

quickstart/quickstart.md
=> add uninstall stuff

gui/actionables/actionables.md, gui/dashboards/dashboards.md, gui/templates/templates.md
=> improve docs on templates, actionables, investigative dashboards.

ingesters/simple_relay.md
=> document simple relay regex listener

quickstart/quickstart.md
=> updating pdf link for training

search/filetype/filetype.md
adds the explicit operators supported and adds some info about the expected format and EV requirements.
=> add some more explanation and the supported filters

ingesters/customtime/customtime.md, ingesters/ingesters.md
=> Add note about time zones with ingestion

search/extractionmodules.md
adding a bunch of info around extraction modules and how acceleration is applied.
closes  #432
=> additional docs around accelerators and query modules 

changelog/5.0.6.md, changelog/list.md
=> 5.0.6 changelog

quickstart/quickstart.md
=> adding updated training link

configuration/accelerators.md
This PR addresses https://github.com/gravwell/wiki/issues/472
=> clarifying the bloom engine as the default

configuration/accelerators.md, ingesters/preprocessors/preprocessors.md
also updating the accelerator benchmark stuff.
=> adjusting docs to match the new normalized Drop-Misses config option

ingesters/simple_relay.md
This PR addresses https://github.com/gravwell/wiki/issues/485
=> fixing up docs on simple relay and adding docs about the RFC6587 reader

configuration/accelerators.md
=> add list of split characters in fulltext

configuration/replication.md
=> improve replication notes

ingesters/preprocessors/jsontimeextract.md, ingesters/preprocessors/preprocessors.md, quickstart/downloads.md
This PR addresses https://github.com/gravwell/wiki/issues/514
=> bringing master in and adding `jsontimeextract` docs page

ingesters/preprocessors/jsontimeextract.md, ingesters/preprocessors/plugin.md, ingesters/preprocessors/preprocessors.md
This PR addresses https://github.com/gravwell/wiki/issues/517
=> Adding in plugin preprocessor docs

quickstart/downloads.md, tools/tools.md
This PR addresses https://github.com/gravwell/wiki/issues/510
https://github.com/gravwell/wiki/issues/522 is needed before this is 100% done
=> adding in link to gravwell tools

tools/tools.md
=> document the tools package a bit

changelog/5.1.3.md, changelog/list.md
This PR proposes adding a changelog for v5.1.3
=> chore: Create 5.1.3.md

README.md, ingesters/customtime/customtime.md
This PR addresses:
-  https://github.com/gravwell/wiki/issues/550
- https://github.com/gravwell/wiki/issues/549
=> fix(#550,#549): timegrinder documentation link & update README

flows/patterns/patterns.md
I checked out #555 when performing a review so that I could build the solution and verify that all the references were valid. I found some other broken links that were not related to #555.
These were introduced in #552.
=> fix broken links

changelog/5.1.4.md, changelog/list.md, conf.py
@michael-wisely-gravwell @ashnwade @john-floren-gravwell  should probably all sign off.
=> laying out change log

ingesters/netflow.md
Discord user called this out... :/
=> remove bad note about netflow v5 support

ingesters/winevent.md
This PR addresses https://github.com/gravwell/wiki/issues/566
=> addressing issue #566

ingesters/file_follow.md
adding some more docs on file follower and a table of params like the other ingesters
This PR addresses https://github.com/gravwell/wiki/issues/568
=> documenting the Attach-Filename parameter

search/ipfix/ipfix.md
I think our markdown parsing got stricter.
=> fix table in ipfix

ingesters/preprocessors/regexextract.md
=> Documenting attach directive for regexextract preprocessor

beta/index.md
This PR addresses https://github.com/gravwell/wiki/issues/594
=> Removed Current State of the Beta

ingesters/http.md
=> add more docs to http ingester: Issue 582

index.md
This PR addresses #586
You can pull the PR and test. 
I tested with several variations including:
http://127.0.0.1:8000/#!metrics.md#Crash_Reporting
http://127.0.0.1:8000/#!architecture/architecture.md
http://127.0.0.1:8000/#!ingesters/file_follow.md#Kernel_parameter_tuning
=> update redirect to fix anchor rewrites

search/kv/kv.md
=> document -dall in kv module

conf.py
=> Update `conf.py` with new release version

search/eval/eval.md
=> update eval documentation for hoc

ingesters/collectd.md, ingesters/eventhubs.md, ingesters/federators/kafkafederator.md, ingesters/file_follow.md, ingesters/http.md, ingesters/installation_instructions_template.md, ingesters/ipmi.md, ingesters/kafka.md, ingesters/kinesis.md, ingesters/msg.md, ingesters/netflow.md, ingesters/o365.md, ingesters/packetfleet.md, ingesters/pcap.md, ingesters/pubsub.md, ingesters/s3.md, ingesters/shodan.md, ingesters/simple_relay.md, ingesters/snmp.md, ingesters/sqs.md, quickstart/quickstart.md
Uses a template rather than duplicating everything.
This PR addresses #581
=> Roll installation instructions in each ingester page.

search/time/time.md
=> add note on -f in the time module

changelog/5.2.1.md, changelog/list.md, conf.py, quickstart/quickstart.md
Starting the 5.2.1 changelog with some frontend changes.
=> starting 5.2.1 changelog

configuration/environment-variables.md
This PR addresses https://github.com/gravwell/wiki/issues/649
We had a fourth column alignment cell in a three-column table. 
This PR proposes removing that unnecessary cell.
=> fix: Remove unnecessary cell from table

search/search.md
This PR addresses https://github.com/gravwell/wiki/issues/652
=> fix(#652): Fit video to width

search/search.md, search/slice/slice.md
This PR addresses no issue. Merge master to dev.
=> chore: merge master to dev

search/eval/eval.md
=> add language on eval has() and undefined behavior

configuration/ageout.md, configuration/parameters.md
This PR addresses https://github.com/gravwell/wiki/issues/667
=> adding docs about Required-Retention

configuration/networking.md, quickstart/quickstart.md
adding more language to the note and making it a warning as well as showing --permanent flag
=> Make redhat firewall commands more in your face.

changelog/5.2.2.md, changelog/list.md, conf.py, configuration/compression.md, configuration/parameters.md, ingesters/netflow.md
This PR:
- Adds the changelog for the v5.2.2 release
- Updates the current version list
- Fixes formatting on some of the configuration pages that were hard to read
=> 5.2.2 changelog

quickstart/quickstart.md
This PR addresses no issue. Updates training link for 5.2.2
=> update training link

changelog/5.2.2.md
This PR addresses no issue. The release date was already fixed live, but this PR updates the documentation in the repo so that it is fixed for next time.
=> Fix 5.2.2 release date

ingesters/file_follow.md
There is already kernel tuning, Redhat, and startup consideration sections. This just adds another attention block for kernel tuning.
Fixes #684
=> Add more file follower tuning callouts

tools/tools.md
This PR updates https://github.com/gravwell/wiki/issues/696
=> Addition: AccountUnlock added to gravwell Tools documentation.

ingesters/simple_relay.md
we were missing some options on the JSON listener
=> adding missing config options

search/trim/trim.md
=> add -e and example to trim module documentation

.gitignore, admin/backuprestore.md
This PR addresses https://github.com/gravwell/wiki/issues/724
=> add automated backup block in backup/restore section

distributed/frontend.md
=> indicate which operations need a datastore connection

.gitignore, configuration/parameters.md
This PR addresses https://github.com/gravwell/wiki/issues/728
=> Add missing config parameters

changelog/5.3.3.md, changelog/list.md, conf.py
=> adding in 5.3.3 change log

distributed/frontend.md, scripting/searchagent.md
=> document searchagent HA

search/eval/eval.md
Update eval documentation around:
- break/continue
- return
- persistent variables
- acceleration
- true/false
- other nits
=> eval language update, part 1

configuration/certificates.md
update gencert -h to -host
bring master commit back into dev
=> Update certificates.md - cherry pick

changelog/5.3.4.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR:
- adds a changelog for 5.3.4
- updates the changelog list
- updates the version in `conf.py`
- updates the link to the training pdf
=> adding in 5.3.4 change log

search/packet/packet.md
moving an example that was akwardly placed and adding clarification on the Modbus layer
=> Cleaning up some packet docs.

search/search.md, search/spec.md
=> add double slash comment documentation

ingesters/s3.md, ingesters/sqs.md
=> add s3/sqs documentation, as well as Credentials-Type info.

search/ip/ip.md
=> add example for multiple IP filters without the or flag.

3rdparty-frontend-licenses.txt, changelog/5.3.4.md, changelog/5.4.0.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. This is the changelog for the v5.4.0 release. 
I did not include bugs that were introduced and fixed within this development cycle.
=> 5.4.0 changelog

ingesters/win_file_follow.md, ingesters/winevent.md
This PR addresses no issue. Updates the download links for the windows ingesters.
=> update download links for windows ingesters

flows/nodes/slackfile.md, flows/nodes/slackmessage.md, ingesters/s3.md
to also indicate which authentication scopes are required
=> updating the slack flow nodes

ingesters/http.md, search/json/json.md, search/taint/taint.md, search/unique/unique.md
Fixes #803
Fixes #802
Fixes #796
Fixes #795
=> various fixes

changelog/5.4.1.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. Updating the changelog and training pdf for 5.4.1
=> start 5.4.1 changelog

search/ipexist/ipexist.md
This PR addresses no issue. Fixes the link to the ipexist library in the documentation.
=> fix link to ipexist library

ingesters/s3.md
=> add documentation on Worker-Pool-Size in the S3 ingester

ingesters/http.md
=> addressing bad tag match docs

configuration/email.md
=> fix typo in shared mail config

changelog/5.4.2.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. Starting changelog for v5.4.2 release.
=> chore: 5.4.2 changelog

ingesters/customtime/customtime.md, ingesters/preprocessors/regextimestamp.md
=> document Extraction-Regex

3rdparty-frontend-licenses.txt, changelog/5.4.2.md, changelog/5.4.3.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR includes:
- changelog for v5.4.3
- updated training link
- updated 3rd party licenses for frontend
Please review for accuracy, punctuation. Make sure that I didn't miss anything important. You can refer to the project board too. 
I would like a frontend, backend/ingesters, and a kit review.
=> Changelog for 5.4.3

flows/nodes/teams.md
just adding some docs and a link.
=> adding incoming webhook docs to teams node

_templates/git-commit-footer.html, conf.py
This PR ...
- fixes https://github.com/gravwell/wiki/issues/869
- fixes https://github.com/gravwell/wiki/issues/870
=> enhancement: Footer improvements

search/firstlast/firstlast.md
=> add examples to first/last

ingesters/federators/federator.md
This PR addresses https://github.com/gravwell/wiki/issues/878
=> documenting new federator flags

ingesters/ingesters.md
The other asks in issue 868 are already in the timegrinder section in the ingesters page.
Fixes #868
=> ingesters: add list of timestamp formats for time grinder

flows/nodes/mattermost.md
This PR addresses https://github.com/gravwell/wiki/issues/888
=> Added new fields for Mattermost Message node

ingesters/msg.md
=> change colliding state files in example on msgraph

ingesters/ingesters.md
This PR addresses some of https://github.com/gravwell/wiki/issues/897
=> documenting ingest-secret-file config

_static/versions.json, changelog/5.4.5.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. Starting the changelog for v5.4.5
=> Changelog for v5.4.5

search/chart/chart.md
This PR addresses https://github.com/gravwell/wiki/issues/934
=> task(#934): Update language related to chart limit/other

ingesters/collectd.md
Add some additional info to make the collectd ingester more in line with the others.
This PR addresses https://github.com/gravwell/wiki/issues/937
=> add some additional docs to collectd

ingesters/http.md
=> Add amazon firehose documentation.

cbac/cbac.md
This PR addresses https://github.com/gravwell/wiki/issues/943
=> fix(#943): Update SOAREmail capability description

_static/versions.json, changelog/5.4.6.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> v5.4.6 changelog

3rdparty-frontend-licenses.txt, _static/versions.json, changelog/5.4.7.md, changelog/list.md, conf.py, quickstart/quickstart.md
Starting the changelog for v5.4.7.
=> start 5.4.7 changelog

changelog/5.4.7.md
This PR addresses no issue. Update the release date for v5.4.7
=> Changelog: Update release date for v5.4.7

configuration/docker.md
This PR addresses https://github.com/gravwell/wiki/issues/970
=> Fix broken link

configuration/docker.md, ingesters/simple_relay.md
Backport corrections from: 
- #965 
- #968 
- #972
=> Corrections: Release v5.4.3

_static/versions.json, changelog/5.4.8.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.4.8 release
=> v5.4.8 Changelog

search/eval/eval.md
Documents the new eval pretty print functions:
- pretty_size
- pretty_count
- pretty_rate
- pretty_line_rate
=> document new eval pretty print functions

_static/versions.json, changelog/5.4.9.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release v5.4.9 changelog

ingesters/file_follow.md
This PR addresses no issue. Correction for Regex-Delimiter description.
=> Fix regex-delimiter description

quickstart/downloads.md
=> Release/v5.4.10: Fix macos hash

ingesters/file_follow.md, ingesters/http.md
This PR addresses https://github.com/gravwell/wiki/issues/1034
=> Release/v5.4.7: Fix HTTP ingester token name

search/eval/eval.md
This PR addresses no issue. Removes duplicated math function documentation for eval.
=> Release/v5.4.9: Remove duplicate math functions

configuration/environment-variables.md
This PR addresses no issue. Fixes a myst warning. This correction has already been made on later versions of the doc.
=> Release/v5.4.4: Fix myst

ingesters/file_follow.md, ingesters/http.md, ingesters/kafka.md
=> Release/v5.4.4: fix Kafka ingester

conf.py
=> Release/v5.4.7: Avoid building files in .github

glossary/glossary.md, quickstart/quickstart.md
=> Release/v5.4.8: Fix myst

search/search.md
=> add time constraint documentation

3rdparty-frontend-licenses.txt, _static/versions.json, changelog/5.5.0.md, changelog/list.md, conf.py, quickstart/quickstart.md, search/search.md, tools/tools.md
=> Release/v5.5.0: Changelog

.github/workflows/build-html.yml
We renamed the `master` branch to `main` to be consistent with GitHub default and other repos.
=> Release/v5.5.0: Fix build

3rdparty-frontend-licenses.txt, _static/versions.json, changelog/5.5.1.md, changelog/list.md, conf.py, quickstart/quickstart.md
Updating changelog for v5.5.1 release.
=> Release/v5.5.1: Changelog

_static/versions.json, changelog/5.5.2.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.5.2: Changelog

3rdparty-frontend-licenses.txt, _static/versions.json, changelog/5.5.3.md, changelog/list.md, conf.py, quickstart/quickstart.md
Update changelog for release v5.5.3.
=> Release/v5.5.3: Changelog

changelog/5.5.6.md
This PR addresses no issue. Fix a typo in the changelog.
=> Release/v5.5.6: Fix typo

_static/versions.json, changelog/5.5.7.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.5.7: Changelog

architecture/architecture.md, conf.py, configuration/filesystems.md
This PR addresses no issues.
I recently reviewed and approved https://github.com/gravwell/wiki/pull/1169
but it occurred to me that Kris had added a page and that I should try building it to see if there were any warnings. 
I fixed the warnings resulting from that PR as well as some warnings related to https://github.com/gravwell/wiki/pull/1149
=> Chore: Address warnings

conf.py
=> chore: Merge v5.5.7 to main

3rdparty-frontend-licenses.txt, _static/versions.json, changelog/5.6.0.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. Changelog for v5.6.0 release.
=> Release/v5.6.0: Changelog

changelog/5.6.0.md
This PR addresses no issue. Updating the 5.6.0 release date.
=> Chore: Update release date for 5.6.0

_static/versions.json, changelog/5.6.1.md, changelog/list.md, conf.py, quickstart/quickstart.md
This PR addresses no issue. Adds changelog for v5.6.1 release.
=> Release/v5.6.1: Changelog

_static/versions.json, changelog/5.6.2.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.2: Changelog

_static/versions.json, changelog/5.6.3.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.6.3 release.
=> Release/v5.6.3: Changelog

ingesters/preprocessors/jsonextract.md
Apparently there was some confusion RE this issue: https://github.com/gravwell/gravwell/issues/1036
so this cleans up some wording
=> clean up some wording

_static/versions.json, changelog/5.6.4.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.4: Changelog

_static/versions.json, changelog/5.6.5.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.5: Changelog

_static/versions.json, changelog/5.6.6.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.6: Changelog

search/search.md
=> fixing timestamp examples

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/task.md
=> Task: Update issue templates

_static/versions.json, changelog/5.6.7.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.6.7 release.
=> Release/v5.6.7: Changelog

eula.md
This PR proposes updating the address listed in the EULA.
=> Update EULA address

search/regex/regex.md
=> Enhance regex documentation a bit

_static/versions.json, changelog/5.6.8.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.8: Changelog

flows/flows.md
=> Document the default fields found in the flow payloads.

quickstart/quickstart.md
small wording tweaks to call out latest and greatest from both AMD64 companies.
=> remove manufacturer name and call out both of the latest and greatest

_static/versions.json, changelog/5.6.9.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.6.9: Changelog

alerts/alerts.md, automation.md, flows/flows.md
Warnings around potential security risks in using flows owned by other users.
Addresses #1344
=> Be more explicit about how consumer flows are executed.

gui/persistent/persistent.md, gui/queries/queries.md
This PR addresses https://github.com/gravwell/wiki/issues/1348
=> Update links from persistent searches page

_static/versions.json, changelog/5.6.10.md, changelog/list.md, conf.py
Changelog for the v5.6.10 release.
=> Release/v5.6.10: changelog

configuration/parameters.md, search/search.md
=> fix language on compound query limits.

search/search.md
=> add language on temporal vs non-temporal

ingesters/http.md
This PR addresses https://github.com/gravwell/wiki/issues/1349
=> add docs around max concurrent stuff for HTTP ingester

ingesters/kafka.md, quickstart/quickstart.md
This PR addresses: https://github.com/gravwell/wiki/issues/1364
=> Tweak kafka config docs and fix typo

configuration/replication.md
This PR addresses no specific issue but documents a new configuration feature
=> document Database-Path replication config

ingesters/simple_relay.md
=> Add section on TLS to simple relay docs

changelog/5.7.0.md
This PR addresses no issue. Updates the changelog to include information about v5.7.0-2 hotfix.
=> Release/v5.7.0: Add hotfix and correct release date

_static/versions.json, changelog/5.7.1.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.7.1: Changelog

configuration/sso.md, flows/nodes/throttle.md
Document Enable-Verbose-Logging in sso.md and add some sample queries for the logs, per #1390
Document the optional nature of Throttle node keys, per #1401
=> SSO & throttle node tweaks

changelog/5.7.1.md
Adds an improvement to the changelog that was missed earlier.
=> Release/v5.7.1: Add bullet for SSO logging to Changelog

changelog/5.7.1.md
Correction for release v5.7.1 changelog.
=> Release/v5.7.1: Changelog correction

changelog/5.7.1.md
Correction made for Release v5.7.1 changelog.
=> Release/v5.7.1: Merge changelog correction to main

_static/versions.json, changelog/5.7.2.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.7.2: Changelog

changelog/5.7.2.md
Update changelog for v5.7.2 release.
=> Release/v5.7.2: added bullet point to changelog

configuration/replication.md
=> remove duplicated config option

ingesters/federators/federator.md
=> Document timestamp max deltas for federator

_static/versions.json, changelog/5.7.3.md, changelog/list.md, conf.py, configuration/parameters.md, ingesters/federators/federator.md, license/license.md, quickstart/quickstart.md
Changelog for the v5.7.3 release.
=> Release/v5.7.3: Changelog

changelog/5.7.0.md, changelog/5.7.3.md
Add hot fix changes to release v5.7.3 changelog. 
Edit previous changelog hotfix title for consistency.
=> Release/v5.7.3: Add hotfix to changelog

_static/versions.json, changelog/5.7.4.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.7.4: Changelog

configuration/ditto.md
=> fix up ditto docs

_static/versions.json, changelog/5.7.5.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.7.5: Changelog

ingesters/winevent.md
=> Document parameters for winevent

search/packet/packet.md
=> add icmpv6 to packet module documentation

search/maclookup/maclookup.md
=> Document mac prefix database

ingesters/http.md
This PR addresses https://github.com/gravwell/wiki/issues/1477
=> fix(#1477): fix typo on http ingester page

search/eval/eval.md
=> add some eval examples

configuration/sso.md
This PR addresses https://github.com/gravwell/wiki/issues/1491
=> fix(#1491): add note about SAML group limits

configuration/sso.md
also move around a note about max groups
=> Document large sessions support in SSO

_static/versions.json, changelog/5.7.7.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.7.7 release.
=> Release/v5.7.7: Changelog

configuration/archive.md, flows/nodes/http.md, flows/nodes/mattermost.md
This PR addresses https://github.com/gravwell/wiki/issues/1499
=> Add a note about truncating payloads in the Mattermost node.

search/eval/eval.md
No PR addressed...found small spelling mistake
=> Spelling correction

_static/versions.json, changelog/5.7.8.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.7.8 release.
=> Release/v5.7.8: Changelog

configuration/ditto.md
=> document some ditto caveats

_static/versions.json, changelog/5.7.9.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.7.9: Changelog

configuration/parameters.md
This PR addresses https://github.com/gravwell/wiki/issues/1523
=> addressing missing `Database-Path` parameter in complete config list

search/eval/eval.md
=> fix example in eval

configuration/archive.md
This PR addresses https://github.com/gravwell/wiki/issues/1544
=> document S3 cloud archive and add some more info on other backends

CONTRIBUTING.md, conf.py
=> Add CONTRIBUTING.md

flows/nodes/teams.md
This PR addresses https://github.com/gravwell/wiki/issues/1558
=> update links on teams flow node docs

configuration/parameters.md, configuration/replication.md
This PR addresses https://github.com/gravwell/wiki/issues/1552
=> Add delete delay and storage reserve to replication docs

_static/versions.json, changelog/5.8.0.md, changelog/list.md, conf.py, configuration/archive.md, configuration/parameters.md, quickstart/quickstart.md, search/eval/eval.md, search/search.md, search/transaction/transaction.md
Changelog for the v5.8.0 release.
=> Release/v5.8.0: Changelog

quickstart/quickstart.md
=> Add webserver stuff to hardware calculator in quickstart

search/search.md
=> Add note to time constraint documentation

changelog/5.8.1.md
Update the changelog for v5.8.2-1.
=> Release/v5.8.1-2: Update changelog for v5.8.1-2

_static/versions.json, changelog/5.8.3.md, changelog/list.md, conf.py, quickstart/quickstart.md
=> Release/v5.8.3: Changelog

flows/nodes/email.md, flows/nodes/http.md
=> Document automatic conversions in email and http nodes

_static/versions.json, changelog/5.8.4.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.8.4 release.
=> Release/v5.8.4: Changelog

_static/versions.json, changelog/5.8.5.md, changelog/5.8.6.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.8.6 release.
=> Release/v5.8.6: Changelog

changelog/5.8.6.md
Fix changelog version and date for v5.8.6 release.
=> Fix changelog version and date

changelog/5.8.6.md
Fix version number and date in the v5.8.6 changelog.
=> Release/v5.8.6: Fix version number and date

scripting/scriptingsearch.md
getSecret was not documented in the scripting functions list
This PR addresses no specific issue
=> document getSecret function for scripting

search/eval/eval.md
=> document new JSON functions for eval

_static/versions.json, changelog/5.8.7.md, changelog/list.md, conf.py, quickstart/quickstart.md
Changelog for the v5.8.7 release.
=> Release/v5.8.7: Changelog
