serve.go

Updated the search JSON marshaler so that it sends empty arrays rather than `null` when there aren't any search results
Also updated the sorting system so that changelog entries are always last.

updating sort order and fixing encoding on search results

---

assets/js/search.js

If the search bar element isn't available, just set a half-second timeout and look for it again.
Fixes #59

Set style after search bar element is available

---

changelog/4.0.1.md
changelog/list.md
ingesters/preprocessors/preprocessors.md

Adding in changelog
Cleaning up some preprocessor documentation and adding documentation for the gravwellforwarder preprocessor.
Should cover issue #30 (https://github.com/gravwell/wiki/issues/30)
Also explicitely calling out the type of each preprocessor.

changelog and preprocessor docs

---

search/search.md

I had this table alphabetized, but our wiki doesn't render the last cell correctly if it's empty (lookup has no notes), so I put anko at the bottom on purpose...

add enrich module to table of supported compound query modules

---

api/kits.md

Adding additional fields found in the Kit Build Request to the API documentation.
Also adding an example with the Cover, banner, icon items and embedded items such as a license.

Addressing issue 147

---

ingesters/customtime/customtime.md

The list of ingesters themselves is correct.
Closes #254

update links on custom timestamp supported ingesters.

---

search/spec.md

This PR addresses https://github.com/gravwell/wiki/issues/454

fix(454): Link to compound query notation

---

beta/index.md

key wasn't referenced in echo command to get beta repo stood up

fixing command for apt repo on beta repo

---

_static/css/custom.css

This PR proposes allowing the docs page to grow in width with the user's browser window. This should help with some readability issues related to horizontal-scroll / word wrap.

feat: Allow for wider content

---

configuration/docker.md
ingesters/netflow.md

also calling out port used by Cisco and friends
Discord user called out the docs examples weren't matching the defaults in the config which is confusing when starting up.  This makes the docs match the config.

updating the docs to show the right default port on netflow ingester

---

README.md
_static/css/custom.css
conf.py
ingesters/installation_instructions_template
packages.nix

This PR addresses #655 
This PR proposes adding a "copy" button to...
- the `<pre>` command blocks on ingester pages that show install instructions
- all other code blocks
The relevant issue requests that the command work on the command blocks, but I figured it might not hurt to expand the scope to other config stuff as well. It's pretty convenient to just click-to-copy config chunks.

feat: Add copy button to code elements

---

changelog/5.2.2.md

This PR addresses no issue. Fixes broken link for Syslog Router preprocessor in changelog

fix: broken link in changelog

---

configuration/archive.md
index.md
ingesters/ingesters.md
ingesters/win_file_follow.md
ingesters/winevent.md
quickstart/downloads.md
quickstart/quickstart.md
search/math/math.md

This PR addresses:
- https://github.com/gravwell/wiki/issues/747
- https://github.com/gravwell/wiki/issues/748
This PR:
- Removes `.md` from links to other pages
- Promotes Downloads to the top nav menu
- Moves API under the More menu option in the top nav
- Adds the link to download installers to the Windows ingester pages only - I did not do this for other ingesters
Please note that you will need to run `make clean` before you run `make html` in order for all of the pages to update properly with the new top nav menu. Maybe you do this already, but wanted to mention it just in case.

fix(#747, #748): promote downloads + remove .md from links

---

search/math/math.md
search/processingmodules.md
search/unique/unique.md

Addresses #782
Turns out that the way the toctree stuff works makes it hard to split out separate entries linking to sum, count etc. so that will have to happen another time.

split unique to its own page

---

packages.nix

This PR proposes upgrading `pydata-sphinx-theme` to version 0.15.2. 
The update includes a change that was built into `_vendor/pydata_sphinx_theme-0.15.1-py3-none-any.whl`. Now that the change is upstream, there's no need to include the wheel in our repo.
The update also seems to address https://github.com/gravwell/wiki/issues/871 by pulling in an upstream fix.

chore: Upgrade theme to version 0.15.2

---

ingesters/s3.md

add File-Filters language to sqs/sns listeners as well. Slight reorganization

---

_static/css/custom.css
_templates/dynamic-navbar.html
_templates/layout.html
_templates/sections/header.html
conf.py

This PR addresses https://github.com/gravwell/wiki/issues/876
This PR proposes:
- Modifying the component that contains header links (`navbar_center`), so that the links in the nav bar hide/show themselves as the width of the browser window changes.
- Fixing a search issue (pydata-sphinx-theme/1676) by adding a `role="main"`

Dynamically show/hide links to improve navbar responsiveness

---

ingesters/s3.md

Adding section with example AWS IAM Permissions policies to the s3.md wiki page.
This PR addresses a potential gap in documentation that can lead to client difficulties in syncing with their AWS Account.    No Issue was created.

[Doc Enhancement ]  Updating S3 doc page with example AWS Permissions Policies

---

ingesters/s3.md

Replaced "Visual Editor" Sid names with more descriptive Gravwell naming within the example AWS Permission Policies
This PR addresses a lack of professional polish on the original example policies

[Documentation Enhancement ] Updated S3 Permissions policy SID

---

changelog/5.4.4.md
changelog/list.md
conf.py
quickstart/quickstart.md

This PR addresses no issue. Starting the changelog for v5.4.4 release.

v5.4.4 Changelog

---

_static/versions.json

The version list must be updated prior to release to ensure that the version switcher in the docs behaves properly.

Update versions.json for v5.4.4 release

---

_static/css/custom.css

This PR proposes a style change that hides all but the 8-link navbar when the window is less than 960px and the links are in the left sidebar.
This PR turns [this situation](https://github.com/gravwell/wiki/assets/108433848/7d52ac8b-2af5-4f61-9b1d-10594b4b8a51) into [this](https://github.com/gravwell/wiki/assets/108433848/205c838e-2694-4bd6-a396-69407d09ad25).

Don't show repeated links in sidebar menu

---

ingesters/http.md

Add documentation about the HTTP HEC `Routed-Token-Value`
This PR addresses https://github.com/gravwell/wiki/issues/913

documenting Routed-Token-Type for HEC ingester

---

search/directquery/directquery.md

This PR addresses no issue. Back port a fix for a typo. Fixed in `master` by https://github.com/gravwell/wiki/pull/942

backport fix for typo

---

ingesters/simple_relay.md

Removed "Currently there are two types of listeners (line and RFC5424)." from line 141 as additional Reader types have been added.

Cleanup:  Updated Simple Relay docs to remove reference to only 2 reader types

---

.github/workflows/build-html.yml
conf.py

This PR proposes adding a manually-dispatched workflow that deposits a multi-version, HTML build of the docs as an artifact on GitHub.
Note that this PR must be merged to the default branch of this repository before the workflow becomes available for dispatch. That said, I've executed this workflow on my fork. You can see what the outcome looks like over there: https://github.com/michael-wisely-gravwell/wiki/actions/runs/8900711566

Add workflow to build HTML

---

ingesters/preprocessors/plugin.md

Discord user called out that we don't document the debug process very well, so here is some additional info.
Plus a typo fix.

add section on preprocessor plugins for debugging and verbose output

---

search/eval/eval.md

This PR addresses no issue, but it came to my attention because https://github.com/gravwell/wiki/issues/1007 was submitted. I was looking to see if the duplicate `pretty_count` should just be removed or if it was a copy/paste error that was intended to be edited into some other `pretty_*` function. It looks like all of the `pretty_*` functions were documented, but it got published too soon.

Remove pretty_* functions that should not be included until 5.5.0

---

ingesters/http.md

This PR addresses https://github.com/gravwell/wiki/issues/1034

Release/v5.4.6: Fix HTTP ingester token name

---

tools/tools.md

Not to be merged before 5.5.0 release.
Addresses #1005

Document the updates to the account unlock tool

---

search/eval/eval.md

This PR addresses https://github.com/gravwell/wiki/issues/1007
These functions were published too soon due to some unplanned patch releases. The functions were [removed from the documentation](https://github.com/gravwell/wiki/pull/1009) pending the 5.5.0 release. When these functions were originally documented, `pretty_count` was mistakenly listed twice. That duplicate has been removed in this PR.

pretty functions with duplicate removed

---

ingesters/http.md
ingesters/kafka.md

They had fallen out of date with the actual code.
Addresses gravwell/wiki#1047

Fix up Kafka ingester docs

---

ingesters/http.md
ingesters/kafka.md

This PR addresses https://github.com/gravwell/wiki/issues/1047
The last update to the Kafka ingester was August 2023. Release v5.4.3 came out in November 2023, so I think it is applicable to make these changes in all of the versioned docs.
Original [PR](https://github.com/gravwell/wiki/pull/1049) submitted by John on dev.

Release/v5.4.3: Fix up Kafka ingester docs

---

.github/workflows/build-html.yml

During the build sequence construct a `robots.txt` file that instructs crawlers to ignore all our historical version sub directories.
This PR addresses https://github.com/gravwell/wiki/issues/838

construct a robots.txt file during build

---

ingesters/kinesis.md

add custom enpoint documentation for kinesis

---

configuration/accelerators.md
configuration/parameters.md

This flag was removed over a year ago. Remove it from docs.

remove long deprecated Accelerate-On-Source configuration option.

---

.github/workflows/build-html.yml

A full wiki build includes multiple versions of the Gravwell docs. Each version is different, but much of the content is the same.
This PR proposes using [`jdupes`](https://manpages.debian.org/bookworm/jdupes/jdupes.1.en.html) to find duplicate files and replace them with soft links. By replacing copies with links, this PR aims to reduce the size of builds.
The workflow changes won't be available until this PR is merged to `main`. Until then, one can see the proposed workflow run on my fork: https://github.com/michael-wisely-gravwell/wiki/actions/runs/10690709826/job/29635873170
Note that the built artifact is [201 MB](https://github.com/michael-wisely-gravwell/wiki/actions/runs/10690709826) with de-duplication compared to [2.01 …

ci: Use jdupes to deduplicate build

---

admin/limits.md

Document render storage & resource size limits a bit more, with suggestions as to how you might re-work your queries or resources to avoid hitting these limits.
Addresses #1107

Improve documentation about limits

---

configuration/certificates.md

Document SANs in certificates

---

resources/resources.md

Question came up in discord, might as well call it out in docs.
This PR addresses no issue

add note about hash used for resources

---

.github/workflows/pr-labels.yml
.github/workflows/sync-branches.yml

This PR proposes adding two automations:
- `Update PR Labels`
- adds a "behind" label to a PR when its head (source) branch falls behind its base (target) branch
- adds a "conflict" label to a PR when its head (source) branch is in conflict with its base (target) branch
- `Sync Branches`
- Opens PRs to keep branches in sync:
- main => next-patch
- next-patch => next-minor
- next-minor => next-major

ci: Pr automations

---

search/eval/eval.md

document else if style statements.

---

_static/versions.json
changelog/5.5.6.md
changelog/list.md
conf.py
quickstart/quickstart.md

Changelog for the v5.5.6 release.

Release/v5.5.6: Changelog

---

changelog/5.5.6.md

This PR addresses no issue. Fixes a typo in the v5.5.6 changelog

Release/v5.5.6: Fix typo

---

conf.py
default.nix

We currently have odd behavior on the deployed GitHub Pages site, where visiting v5.5.5 or older versions of the docs will cause the version switcher to stop working.
This happens because old versions of the docs have `https://docs.gravwell.io/_static/versions.json` hard-coded as the location for the version list. When we load the page from deployed GitHub Pages, the docs attempt a cross-domain fetch to `docs.gravwell.io`, which is not allowed.
This PR proposes updating previous releases of the docs to accept the `VERSION_LIST_URL` variable from Actions. This gives us control over where **every** version of the docs looks for the version list.
I've already applied this idea to my fork of the wiki (https://michael-wisely-gravwell.github.io/wiki/v5.4.5/index.html) …

fix: Use env var to determine version list

---

admin/limits.md

Add note on partial downloads.

---

.github/workflows/build-html.yml

We got a warning about disk space on the last build.
This PR proposes using a large runner that has a lot more disk.

ci: Use WikiBuilder runner for HTML builds

---

search/eval/eval.md

Describe type promotion rules.

---

search/spec.md

document start/end constraints in grav.y spec

---

gui/queries/queries.md
search/search.md

add note about timestamp truncation. Remove erroneous statement about compound queries.

---

configuration/accelerators.md
ingesters/ingesters.md
search/search.md

add more context and links to intrinsic EV documentation

---

search/regex/regex.md

https://github.com/gravwell/wiki/pull/1300 added some new documentation to the regex page.
When reviewing an unrelated PR, I checked it out and built the docs locally. I got a warning about these two missing cross-reference targets. After adding the cross-references, the docs build with 0 warnings.

Fix links in regex docs

---

index.md
quickstart/quickstart.md

Improve the hardware calculator, and add storage calculator

---

conf.py
search_scorer.js

Changelogs often clutter search results, making it challenging to find what one is looking for. Consider what happens when I search for "ingester": [Seven rows of Changelog matches push the match for the "Ingesters" page out of view.](https://github.com/user-attachments/assets/73ae1c84-7eec-4406-b1c6-dfd15cd671d5)
This PR proposes using a Sphinx [search scorer](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_search_scorer) to lower the score of any changelog match.
I chose to reduce the changelog score by 100 because I was seeing Changelog matches with scores in the 70s. Reducing by 100 [doesn't eliminate the changelogs from search results](https://github.com/user-attachments/assets/1653e5ac-4ef9-4eb7-95d6-9a9da1ee5d46) (I think that …

fix: Reduce search match score on changlog docs

---

quickstart/quickstart.md

I realized that I missed updating the training link for the 5.6.10 release, so I wanted to fix that before the next release.

chore: Fix training link

---

changelog/5.7.0.md

Change the header levels for the hotfix in the 5.7.0 changelog because I don't think we need to maintain separate links to the same changelog page on the list page. I don't think we need to tag and re-deploy the 5.7.0 documentation just for this, but I want to correct if for when we do the next patch release.

Release/v5.7.0: Change header levels for hotfix

---

configuration/replication.md
ingesters/http.md

also bring in the change in replication defaults from main due to an earlier PR that went to the wrong branch
Example doesn't use the URL we mention:

fix example in HEC compatible HTTP ingester section

---

configuration/certificates.md

Addresses gravwell/wiki#1530 by highlighting that turning on HTTPS can have consequences for the searchagent

Highlight TLS & search agent a bit

---

configuration/parameters.md
search/ai/ai.md

This PR proposes adding more detail about how we process AI requests on different remote services (i.e., gravwell-hosted and self-hosted).
I was arguing with myself about organization / word choice here, so I'm very open to feedback.

Add more detail to remote AI service section
